version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./backups:/backups
  app:
    image: isurangaperera/ideals:latest
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
    restart: always
  # nginx:
  #   build:
  #     context: ./proxy
  #   links:
  #     - app
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - /home/ubuntu/certs/:/etc/nginx/ssl/:ro
  #   restart: always
volumes:
  db:
    driver: local
