version: "3.9"

services:
  app:
    build:
      context: ./app
    env_file:
      - .env
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    restart: always
  nginx:
    build:
      context: ./proxy
    links:
      - app
    stdin_open: true
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ubuntu/certs/:/etc/nginx/ssl/:ro
    restart: always
