version: "3.9"

services:
  app:
    build:
      context: ./app
    env_file:
      - .dev.env
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - "./app:/opt/app"
  guard:
    build:
      context: ./app
    env_file:
      - .env
    command: bundle exec guard --no-bundler-warning --no-interactions
    volumes:
      - "./app:/opt/app"
volumes:
  guard:
