# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/assumptions', type: :request do
  before(:each) do
    set_session_user
  end
  # This should return the minimal set of attributes required to create a valid
  # Assumption. As you add validations to Assumption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Assumption.create! valid_attributes
      get assumptions_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      assumption = Assumption.create! valid_attributes
      get assumption_url(assumption)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_assumption_url

      # puts response.status
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      assumption = Assumption.create! valid_attributes
      get edit_assumption_url(assumption)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Assumption' do
        expect do
          post assumptions_url, params: { assumption: valid_attributes }
        end.to change(Assumption, :count).by(1)
      end

      it 'redirects to the created assumption' do
        post assumptions_url, params: { assumption: valid_attributes }
        expect(response).to redirect_to(assumption_url(Assumption.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Assumption' do
        expect do
          post assumptions_url, params: { assumption: invalid_attributes }
        end.to change(Assumption, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post assumptions_url, params: { assumption: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested assumption' do
        assumption = Assumption.create! valid_attributes
        patch assumption_url(assumption), params: { assumption: new_attributes }
        assumption.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the assumption' do
        assumption = Assumption.create! valid_attributes
        patch assumption_url(assumption), params: { assumption: new_attributes }
        assumption.reload
        expect(response).to redirect_to(assumption_url(assumption))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        assumption = Assumption.create! valid_attributes
        patch assumption_url(assumption), params: { assumption: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested assumption' do
      assumption = Assumption.create! valid_attributes
      expect do
        delete assumption_url(assumption)
      end.to change(Assumption, :count).by(-1)
    end

    it 'redirects to the assumptions list' do
      assumption = Assumption.create! valid_attributes
      delete assumption_url(assumption)
      expect(response).to redirect_to(assumptions_url)
    end
  end
end
