name: "CI Pipeline - DEVELOPMENT"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker_compose
        run: docker-compose -f docker-compose.prod.yml up -d --build
