name: "CI/CD Pipeline - RELEASE"
on:
  push:
    branches: [ 184418154-deployment#5 ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4
        with:
          ruby-version: '3.1.3'
          bundler-cache: true
      - name: Install packages
        run: bundle install
        working-directory: ./app
      - name: Set up database schema
        run: bin/rails db:migrate
        working-directory: ./app
      - name: Set up database schema
        run: bin/rails db:schema:load
        working-directory: ./app
      - name: Run tests
        run: bin/rake
        working-directory: ./app
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker_compose
        run: docker-compose up -d --build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            ls -la &&
            cd /home/ubuntu/ideals &&
            git checkout dev &&
            git fetch --all &&
            git reset --hard origin/dev &&
            git pull origin dev &&
            docker-compose up -d --build 
            '